name = "GRAD Endgame"
prefix = "grad_endgame"
author = "Ainer, Salbei"
files = [
    "mod.cpp",
    "Adler.paa",
    "LICENSE",
    "README.md"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip grad_endgame_{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
]

[header_exts]
version= "{{git \"id 8\"}}"